name: Build and run unit and integration tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker images
        run: docker-compose build

      - name: Build and run integration tests
        run: |
          docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --exit-code-from test
